Comment out terraform-apply-aws

diff --git a/.github/workflows/terraform-apply-aws.yml b/.github/workflows/terraform-apply-aws.yml
--- a/.github/workflows/terraform-apply-aws.yml
+++ b/.github/workflows/terraform-apply-aws.yml
@@ -1,98 +1,98 @@
-name: 'terraform apply aws'
-on:
-  push:
-    branches:
-      - master
-  pull_request:
-    types: [opened, synchronize]
-jobs:
-  terraform:
-    name: 'Terraform Apply to AWS'
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./aws
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+# name: 'terraform apply aws'
+# on:
+#   push:
+#     branches:
+#       - master
+#   pull_request:
+#     types: [opened, synchronize]
+# jobs:
+#   terraform:
+#     name: 'Terraform Apply to AWS'
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         working-directory: ./aws
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v2
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          # terraform_version: 0.13.0 
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v1
+#         with:
+#           # terraform_version: 0.13.0 
+#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ap-northeast-1
+#       - name: Configure AWS Credentials
+#         uses: aws-actions/configure-aws-credentials@v1
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ap-northeast-1
 
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
+#       - name: Terraform Format
+#         id: fmt
+#         run: terraform fmt -check
 
 
-      - name: Terraform Init
-        id: init
-        env:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run: terraform init
+#       - name: Terraform Init
+#         id: init
+#         env:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#         run: terraform init
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color
-        continue-on-error: true
+#       - name: Terraform Plan
+#         id: plan
+#         run: terraform plan -no-color
+#         continue-on-error: true
 
-      - name: find pr
-        uses: jwalton/gh-find-current-pr@v1
-        id: findPr
-        with:
-          state: open
+#       - name: find pr
+#         uses: jwalton/gh-find-current-pr@v1
+#         id: findPr
+#         with:
+#           state: open
 
-      - name: Update Pull Request
-        uses: actions/github-script@0.9.0
-        if: github.ref != 'refs/heads/master'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-          GITHUB_ISSUE_NUMBER: ${{ steps.findPr.outputs.pr }}
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `
-            ## Terraform Plan of AWS
-            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#       - name: Update Pull Request
+#         uses: actions/github-script@0.9.0
+#         if: github.ref != 'refs/heads/master'
+#         env:
+#           PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#           GITHUB_ISSUE_NUMBER: ${{ steps.findPr.outputs.pr }}
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             const output = `
+#             ## Terraform Plan of AWS
+#             #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#             #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#             #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
 
-            <details><summary>Show Plan</summary>
+#             <details><summary>Show Plan</summary>
 
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+#             \`\`\`\n
+#             ${process.env.PLAN}
+#             \`\`\`
 
-            </details>
+#             </details>
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#             *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-            github.issues.createComment({
-              issue_number: process.env.GITHUB_ISSUE_NUMBER,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+#             github.issues.createComment({
+#               issue_number: process.env.GITHUB_ISSUE_NUMBER,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: output
+#             })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-        run: terraform apply -auto-approve
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+#         run: terraform apply -auto-approve
